VRAM_CONFIG = "DIFFSYNTH_VRAM_CONFIG"
QUANT_CONFIG = "DIFFSYNTH_QUANT_CONFIG"
MODEL_CONFIG = "DIFFSYNTH_MODEL_CONFIG"
MODEL_CONFIG_LIST = "DIFFSYNTH_MODEL_CONFIG_LIST"
VRAM_LIMIT = "DIFFSYNTH_VRAM_LIMIT"
PIPE = "DIFFSYNTH_PIPE"


class AnyType(str):
    def __ne__(self, other):
        return False


ANY = AnyType("*")
